sporc:
  ref: "main"

paths:
  data_rds: "data/ebs_pollock.rds"
  outputs_dir: "analysis/outputs"
  comparison_dir: "analysis/comparisons"
  admb_results_rds: "/Users/jim/_mymods/pollock/results/derived/admb_2024.rds"
  admb_source_root: "/Users/jim/_mymods/pollock/admb"

dimensions:
  n_regions: 1
  n_sexes: 1
  n_fish_fleets: 1
  n_srv_fleets: 3

recruitment:
  do_rec_bias_ramp: 0
  sigmaR_switch: 1
  ln_sigmaR: [0.0, 0.0]
  rec_model: "bh_rec"
  steepness_h: 0.623013
  steepness_is_h: true
  h_spec: "fix"
  sigmaR_spec: "fix"
  init_age_strc: 1
  free_init_age_composition: true
  ln_global_R0: 10
  t_spawn: 0.25
  equil_init_age_strc: 2

biology:
  M_spec: "fix"
  fixed_M:
    age1: 0.9
    age2: 0.45
    age3plus: 0.3
  fit_lengths: 0

movement:
  use_fixed_movement: 1
  Fixed_Movement: null
  do_recruits_move: 0

tagging:
  UseTagging: 0

catch:
  Use_F_pen: 1
  sigmaC_spec: "fix"
  sigmaC: 0.05

fishery:
  fish_idx_type: ["biom"]
  FishAgeComps_LikeType: ["Multinomial"]
  FishLenComps_LikeType: ["none"]
  FishAgeComps_Type: ["agg_Year_1-terminal_Fleet_1"]
  FishLenComps_Type: ["none_Year_1-terminal_Fleet_1"]

fishery_selectivity:
  fish_sel_blocks: ["none_Fleet_1"]
  fish_sel_model: ["dbnrml_Fleet_1"]
  fish_q_blocks: ["none_Fleet_1"]
  fish_fixed_sel_pars_spec: ["est_all"]
  fish_fixed_sel_pars_start: [-0.9163, -1.3850, 1.6094, 1.9459, -2.9444, -0.4055]
  fish_q_spec: ["est_all"]

survey:
  srv_idx_type: ["biom", "biom", "biom"]
  SrvAgeComps_LikeType: ["Multinomial", "Multinomial", "none"]
  SrvLenComps_LikeType: ["none", "none", "none"]
  SrvAgeComps_Type:
    - "agg_Year_1-terminal_Fleet_1"
    - "agg_Year_1-terminal_Fleet_2"
    - "none_Year_1-terminal_Fleet_3"
  SrvLenComps_Type:
    - "none_Year_1-terminal_Fleet_1"
    - "none_Year_1-terminal_Fleet_2"
    - "none_Year_1-terminal_Fleet_3"
  srv_sel_blocks: ["none_Fleet_1", "none_Fleet_2", "none_Fleet_3"]
  srv_sel_model: ["logist1_Fleet_1", "logist1_Fleet_2", "logist1_Fleet_3"]
  srv_q_blocks: ["none_Fleet_1", "none_Fleet_2", "none_Fleet_3"]
  srv_fixed_sel_pars_spec: ["fix", "est_all", "est_shared_f_2"]
  srv_fixed_sel_pars_start:
    BTS: [3.0, 1.0]
  srv_q_spec: ["est_all", "est_all", "est_all"]

selectivity_random_effects:
  cont_tv_fish_sel: ["2dar1_Fleet_1"]
  fishsel_pe_pars_spec: "fix"
  fish_sel_devs_spec: "est_all"
  cont_tv_srv_sel: ["iid_Fleet_1", "2dar1_Fleet_2", "2dar1_Fleet_3"]
  srvsel_pe_pars_spec: ["fix", "fix", "fix"]
  srv_sel_devs_spec: ["est_all", "est_all", "est_shared_f_2"]
  corr_opt_fish_semipar: "corr_zero_y_b"
  corr_opt_srv_semipar: [null, "corr_zero_y_b", "corr_zero_y_b"]
  fishsel_pe_pars_log_sigma: 0.30
  srvsel_bts_logistic_log_sigma: 0.075
  srvsel_ats_avo_log_sigma: 0.15
  random_effects: null

weights:
  Wt_Catch: 1
  Wt_FishIdx: 1
  Wt_SrvIdx: 1
  Wt_Rec: 1
  Wt_F: 1
  Wt_Tagging: 0
  Wt_FishAgeComps: 1
  Wt_FishLenComps: 1
  Wt_SrvAgeComps: 1
  Wt_SrvLenComps: 1

fit:
  newton_loops: 3
  silent: false
  base_only: true
